[package]
name = "rustytop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.30.10"
tabled = "0.15.0"
users = "0.11.0"

